# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Website deployment

on:
  push:
    branches: [ react ]
  pull_request:
    branches: [ react ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    
    - name: SSH into digitalocean droplet and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USER }}
        password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
        port: ${{ secrets.DIGITALOCEAN_PORT }}
        script: |
          cd /var/www/thewordtoken.com
          git pull
          npm i --legacy-peer
          npm run build
